using FoxTool.Fox.Types.Values;

namespace FoxTool.Tpp.Classes
{
    public class LipAdjustData : Data
    {
        // Static properties
        public FoxUInt32 OffsetLipA { get; set; }
        public FoxUInt32 OffsetLipAH { get; set; }
        public FoxUInt32 OffsetLipAY { get; set; }
        public FoxUInt32 OffsetLipB { get; set; }
        public FoxUInt32 OffsetLipC { get; set; }
        public FoxUInt32 OffsetLipCH { get; set; }
        public FoxUInt32 OffsetLipD { get; set; }
        public FoxUInt32 OffsetLipE { get; set; }
        public FoxUInt32 OffsetLipEE { get; set; }
        public FoxUInt32 OffsetLipER { get; set; }
        public FoxUInt32 OffsetLipF { get; set; }
        public FoxUInt32 OffsetLipG { get; set; }
        public FoxUInt32 OffsetLipH { get; set; }
        public FoxUInt32 OffsetLipI { get; set; }
        public FoxUInt32 OffsetLipJ { get; set; }
        public FoxUInt32 OffsetLipL { get; set; }
        public FoxUInt32 OffsetLipM { get; set; }
        public FoxUInt32 OffsetLipN { get; set; }
        public FoxUInt32 OffsetLipNG { get; set; }
        public FoxUInt32 OffsetLipOH { get; set; }
        public FoxUInt32 OffsetLipOO { get; set; }
        public FoxUInt32 OffsetLipOU { get; set; }
        public FoxUInt32 OffsetLipOW { get; set; }
        public FoxUInt32 OffsetLipOY { get; set; }
        public FoxUInt32 OffsetLipP { get; set; }
        public FoxUInt32 OffsetLipR { get; set; }
        public FoxUInt32 OffsetLipS { get; set; }
        public FoxUInt32 OffsetLipSH { get; set; }
        public FoxUInt32 OffsetLipT { get; set; }
        public FoxUInt32 OffsetLipTH { get; set; }
        public FoxUInt32 OffsetLipTT { get; set; }
        public FoxUInt32 OffsetLipU { get; set; }
        public FoxUInt32 OffsetLipV { get; set; }
        public FoxUInt32 OffsetLipW { get; set; }
        public FoxUInt32 OffsetLipY { get; set; }
        public FoxUInt32 OffsetLipZ { get; set; }
        public FoxUInt32 OffsetLip_i { get; set; }
        public FoxUInt32 OffsetLip_tH { get; set; }
        public FoxUInt32 AfterSilentOffset { get; set; }
        public FoxUInt32 PreviousSilentOffset { get; set; }
        public FoxFilePtr MotionLipA { get; set; }
        public FoxFilePtr MotionLipAH { get; set; }
        public FoxFilePtr MotionLipAY { get; set; }
        public FoxFilePtr MotionLipB { get; set; }
        public FoxFilePtr MotionLipC { get; set; }
        public FoxFilePtr MotionLipCH { get; set; }
        public FoxFilePtr MotionLipD { get; set; }
        public FoxFilePtr MotionLipE { get; set; }
        public FoxFilePtr MotionLipEE { get; set; }
        public FoxFilePtr MotionLipER { get; set; }
        public FoxFilePtr MotionLipF { get; set; }
        public FoxFilePtr MotionLipG { get; set; }
        public FoxFilePtr MotionLipH { get; set; }
        public FoxFilePtr MotionLipI { get; set; }
        public FoxFilePtr MotionLipJ { get; set; }
        public FoxFilePtr MotionLipL { get; set; }
        public FoxFilePtr MotionLipM { get; set; }
        public FoxFilePtr MotionLipN { get; set; }
        public FoxFilePtr MotionLipNG { get; set; }
        public FoxFilePtr MotionLipOH { get; set; }
        public FoxFilePtr MotionLipOO { get; set; }
        public FoxFilePtr MotionLipOU { get; set; }
        public FoxFilePtr MotionLipOW { get; set; }
        public FoxFilePtr MotionLipOY { get; set; }
        public FoxFilePtr MotionLipP { get; set; }
        public FoxFilePtr MotionLipR { get; set; }
        public FoxFilePtr MotionLipS { get; set; }
        public FoxFilePtr MotionLipSH { get; set; }
        public FoxFilePtr MotionLipT { get; set; }
        public FoxFilePtr MotionLipTH { get; set; }
        public FoxFilePtr MotionLipTT { get; set; }
        public FoxFilePtr MotionLipU { get; set; }
        public FoxFilePtr MotionLipV { get; set; }
        public FoxFilePtr MotionLipW { get; set; }
        public FoxFilePtr MotionLipY { get; set; }
        public FoxFilePtr MotionLipZ { get; set; }
        public FoxFilePtr MotionLip_i { get; set; }
        public FoxFilePtr MotionLip_tH { get; set; }
        public FoxFloat WhisperScl { get; set; }
        public FoxFloat VolumeSameVowelNormal { get; set; }
        public FoxUInt32 LongVoice { get; set; }
        public FoxUInt32 SilentZone { get; set; }
        public FoxFloat MouthSoundRate { get; set; }
        public FoxFloat PreHermiteStartVel { get; set; }
        public FoxFloat PreHermiteEndVel { get; set; }
        public FoxFloat AftHermiteUnivStartVel { get; set; }
        public FoxFloat AftHermiteUnivEndVel { get; set; }
        public FoxFloat AftHermiteLongStartVel { get; set; }
        public FoxFloat AftHermiteLongEndVel { get; set; }
        public FoxUInt32 AdjustPlosionOffset { get; set; }
        public FoxUInt32 PlosionLongOffset { get; set; }
        public FoxFloat PlosionPreTwoRate { get; set; }
        public FoxFloat PlosionPreOneRate { get; set; }
        public FoxFloat PlosionWeight { get; set; }
    }
}
